namespace Util.Domain.Biz.Enums; 

/// <summary>
/// Enumera las diferentes naciones y grupos étnicos.
/// </summary>
public enum Nation {
    [Description( "汉族" )]
    Hz = 0,
    [Description( "蒙古族" )]
    Mgz = 1,
    [Description( "回族" )]
    HuiZ = 2,
    [Description( "藏族" )]
    Zz = 3,
    [Description( "维吾尔族" )]
    Wwez = 4,
    [Description( "苗族" )]
    Mz = 5,
    [Description( "彝族" )]
    Yz = 6,
    [Description( "壮族" )]
    ZhuangZ = 7,
    [Description( "布依族" )]
    Byz = 8,
    [Description( "朝鲜族" )]
    Cxz = 9,
    [Description( "满族" )]
    ManZ = 10,
    [Description( "侗族" )]
    Tz = 11,
    [Description( "瑶族" )]
    YaoZ = 12,
    [Description( "白族" )]
    Bz = 13,//baizu
    [Description( "土家族" )]
    Tjz = 14,
    [Description( "哈尼族" )]
    Hnz = 15,
    [Description( "哈萨克族" )]
    Hskz = 16,
    [Description( "傣族" )]
    Dz = 17,
    [Description( "黎族" )]
    Lz = 18,
    [Description( "傈僳族" )]
    Lsz = 19,
    [Description( "佤族" )]
    Wz = 20,
    [Description( "畲族" )]
    Sz = 21,
    [Description( "高山族" )]
    Gsz = 22,
    [Description( "拉祜族" )]
    Lhz = 23,
    [Description( "水族" )]
    ShuiZ = 24,
    [Description( "东乡族" )]
    Dxz = 25,
    [Description( "纳西族" )]
    Nxz = 26,
    [Description( "景颇族" )]
    Jpz = 27,
    [Description( "柯尔克孜族" )]
    Kekzz = 28,
    [Description( "土族" )]
    TuZ = 29,
    [Description( "达斡尔族" )]
    Dwez = 30,
    [Description( "仫佬族" )]
    Mlz = 31,
    [Description( "羌族" )]
    Qz = 32,
    [Description( "布朗族" )]
    Blz = 33,
    [Description( "撒拉族" )]
    Slz = 34,
    [Description( "毛南族" )]
    Mnz = 35,
    [Description( "仡佬族" )]
    Ylz = 36,
    [Description( "锡伯族" )]
    Xbz = 37,
    [Description( "阿昌族" )]
    Acz = 38,
    [Description( "普米族" )]
    Pmz = 39,
    [Description( "塔吉克族" )]
    Tjkz = 40,
    [Description( "怒族" )]
    Nz = 41,
    [Description( "乌孜别克族" )]
    Wzbkz = 42,
    [Description( "俄罗斯族" )]
    Elsz = 43,
    [Description( "鄂温克族" )]
    Ewkz = 44,
    [Description( "德昂族" )]
    Daz = 45,
    [Description( "保安族" )]
    Baz = 46,
    [Description( "裕固族" )]
    Ygz = 47,
    [Description( "京族" )]
    Jz = 48,
    [Description( "塔塔尔族" )]
    Ttrz = 49,
    [Description( "独龙族" )]
    Dlz = 50,
    [Description( "鄂伦春族" )]
    Elcz = 51,
    [Description( "赫哲族" )]
    Hzz = 52,
    [Description( "门巴族" )]
    Mbz = 53,
    [Description( "珞巴族" )]
    Lbz = 54,
    [Description( "基诺族" )]
    Jnz = 55
}